### ISSUE TITLE
program control arguments

### ISSUE THREAD

**Issue by soeren-kirchner** [soeren-kirchner/pyimgbatch#11]
--logfile logfile (default is pyimgbatch.log in the current folder
--nolog (no logging)
--silent (no output to stdout)

**Comment by tomtomesteves** [comment]
Hello all. Would like to help your repo with that !

**Comment by tomtomesteves** [comment]
I have a doubt about the silent option: the ideia is to remove all outputs, even the bars ?

**Comment by soeren-kirchner** [comment]
hi, thanks for your help offer,
give me some minutes to think about it.

**Comment by soeren-kirchner** [comment]
yes --silent should suppress every output
--no-progress disables the bars

maybe something like --progress-only could be added to disable text output.

**Comment by tomtomesteves** [comment]
Ok ! Will updade the pull request with that.
